### ISSUE TITLE
[1.21.1: NeoForge] Crash on startup with Twilight Forest

### ISSUE THREAD

**Issue by NielsPilgaard** [talhanation/smallships#28] opened 2024-09-25 17:43 UTC
Hi! 👋 

TL;DR: 
`Exception message: net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: smallships:twilightforest:canopy_cog`

SmallShips v`2.0.0-b1.5 `

https://gist.github.com/NielsPilgaard/ae32d7eeb378c1669f9e0e2d207b8022

**Comment by NielsPilgaard** [comment] 2024-10-02 16:52
@talhanation sorry for the ping, I just want to make sure you're aware of this issue 😅

**Comment by Millenial-Kaibaman** [comment] 2024-11-11 07:39
I'm having the same issue with 1.21.1

**Comment by tr1m1n4t0r** [comment] 2024-11-15 10:30
Similar issue with The Aether (in this case `smallships:aether:skyroot_cog`)
Seems like SmallShip tries to generate Ships for the new wood types

`java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'smallships' at 'com.talhanation.smallships.fabric.SmallshipsModFabric'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at knot//net.minecraft.class_310.<init>(class_310.java:477)
	at knot//net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at knot//com.talhanation.smallships.world.item.ModItems.getItem(ModItems.java)
	at knot//com.talhanation.smallships.world.item.ModItems.<clinit>(ModItems.java:16)
	at knot//com.talhanation.smallships.fabric.SmallshipsModFabric.onInitialize(SmallshipsModFabric.java:23)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 6 more
Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: smallships:aether:skyroot_cog
	at knot//net.minecraft.class_2960.method_45137(class_2960.java:285)
	at knot//net.minecraft.class_2960.method_60936(class_2960.java:48)
	at knot//net.minecraft.class_2960.method_60655(class_2960.java:52)
	at knot//com.talhanation.smallships.world.item.fabric.ModItemsImpl.register(ModItemsImpl.java:89)
	at knot//com.talhanation.smallships.world.item.fabric.ModItemsImpl.<clinit>(ModItemsImpl.java:80)
	... 10 more`

**Comment by metroite** [comment] 2024-11-23 18:49
Fixed in PR #34

**Closed as completed by metroite** 2024-11-23 18:49 UTC
